name = "MassProps"
uuid = "5839b151-e113-4d24-b6fd-5f05bf67e06c"
version = "1.0.0-DEV"
authors = ["James Steven Jenkins <sjenkins@studioj.us> and contributors"]

[deps]
ArtifactUtils = "8b73e784-e7d8-4ea5-973d-377fed4e3bce"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
RollupTree = "04c01c7a-6a3c-48fe-9315-f55725a63c92"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
ArtifactUtils = "0.2.4"
Artifacts = "1.11.0"
CSV = "0.10.15"
DataFrames = "1.8.1"
LinearAlgebra = "1.12.0"
MetaGraphsNext = "0.8.0"
RollupTree = "1.0.0"
TestItems = "1.0.0"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
